import React, { useContext } from "react";
import Head from "next/head";
import Sidebar from "./sidebar";
import Navbar from "./navbar";
import { withMinumumStaffRole } from "./rbac-hoc";

function Page({ Role, Component, pageProps, title = "Title" }) {
    let RestrictedPageComponent = withMinumumStaffRole(Role)(Component);
    return (
        <>
            <div>
                <Head>
                    <title>{title}</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    <Navbar />
                    <Sidebar />
                    <div id="page-container">
                        <RestrictedPageComponent
                            {...pageProps}
                            showIfNotAuthorized={true}
                        />
                    </div>
                </main>
            </div>
        </>
    );
}

export default Page;
